name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Pharo
        run: |
          Invoke-WebRequest -Uri https://files.pharo.org/get-files/130/pharo-vm-Windows-x86_64-stable.zip -OutFile pharo-vm-Windows-x86_64-stable.zip
          unzip pharo-vm-Windows-x86_64-stable.zip -d pharo-vm
          dir
